### ISSUE TITLE
Error in isolinux.cfg

### ISSUE THREAD

**Issue by Surfer2010** [philpagel/debian-headless#1]
i geht the Error
"Loading /install.i386/vmlinuz failed: No such file or directory"

possible to have a problem with the relative/absolut path?
Hope to get help on this one

Thanks great Tutorial

**Comment by philpagel** [comment]
From the top of my head I'm not sure. I think I'd need more information on what exactly you did and what happened at what point. E.g. which Debian image, what did you configure, what did you run and did that go w/o errors, etc.

One observation, though: The correct path for `vmlinuz` on i386 (i.e. 32bit kernel) would be `install.386` not `install.i386`. Did you set the `ARCH` variable to "i386" by any chance?

**Comment by Surfer2010** [comment]
Hello, i used this image https://cdimage.debian.org/debian-cd/current/i386/iso-cd/debian-10.3.0-i386-netinst.iso

here my steps:

# make a tmp folder
	mkdir isofilei386
# unpack the iso
	bsdtar -C isofilei386 -xf debian-10.3.0-i386-netinst.iso
# Set write permissions
	chmod -R +w isofilei386
Nun liegt alles schön im isofilei386/ folder und dort können wir unser Installationsmedium nun nach Herzenslust modifizieren.

Also erstmal cd isofilei386 und dort das File isolinux/isolinux.cfg löschen und ein Neues mit diesem Inhalt erzeugen:
	cd isofilei386
	rm isolinux/isolinux.cfg
	nano isolinux/isolinux.cfg

	DEFAULT install
		SAY Now booting the debian installer
	LABEL install
		kernel /install.386/vmlinuz
		append vga=788 initrd=/install.386/initrd.gz --- quiet
	Preseeding
Als nächstes brauchen wir ein preseeding File (preseed.cfg). Ein typisches für eine deutschsprachige Installation sieht so aus:
	
	nano isolinux/preseed.cfg

#### Contents of the preconfiguration file (for stretch)
	d-i debian-installer/locale select de_DE
	d-i console-keymaps-at/keymap select de
	d-i keyboard-configuration/xkb-keymap select de

	d-i netcfg/choose_interface select auto
	d-i netcfg/get_hostname string wintermute 
	d-i netcfg/get_domain string local
	d-i netcfg/hostname string wintermute

	d-i hw-detect/load_firmware boolean true

	d-i network-console/password password install
	d-i network-console/password-again password install
	d-i network-console/start select continue

# initrd auspacken
	gunzip install.386/initrd.gz
# preseed file rein
	echo isolinux/preseed.cfg | cpio -H newc -o -A -F install.386/initrd
# und wieder einpacken
	gzip install.386/initrd
# MD5 sums aktualisieren
Und damit der Installer nicht meckert müssen wir nun die MD5 sums auf den neusten Stand bringen:

    find ./ -type f -exec md5sum {} \; > md5sum.txt
Fertig – unser Installationsmedium ist inhaltlich präpariert.

Darf ich Ihnen das einpacken?

	cd ..
	
# create iso
	genisoimage -V Debian-headless -r -J -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o debian-10.3.0-i386-netinst-headless.iso isofilei386
# fix MBR
	isohybrid debian-10.3.0-i386-netinst-headless.iso
Auf den Stick damit (WINDOWS --> https://www.balena.io/etcher/)

**Comment by philpagel** [comment]
Ah – ok so you are following the tutorial on my blog?
Can you please try out the version provided here on github? I want to make sure the process itself didn't break. At least it didn't for me: I just used that very same image and performed a dry run with qemu which happily booted into the installer.

**Comment by philpagel** [comment]
And double check `isolinux/isolinux.cfg`: Based on your error message, I suspect it says `kernel /install.i386/vmlinuz` instead of  `kernel /install.386/vmlinuz`...

**Comment by Surfer2010** [comment]
i double checked, and you're right there is an "i" too much ^^
so i corrected this, now it stopped at choosing a language in the installation process (on the testing device i do have a screen and keyboard but i need it on a different machine headless)
are you on any irc channel would be easier

**Comment by philpagel** [comment]
That means that the system could not find your preseeding file. Please use the wrapped up version provided here on github to make sure that it works before going forward, manually. Once you know that works you can easily look up all the steps in the Makefile and modify from there.

**Comment by philpagel** [comment]
No additional message in a week – so I assume the problem did not occur in the version supplied on github.
