### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by ksawery29** [philpagel/debian-headless#10]
While running `make download` it is throwing 404 not found error. Please update the url

```
HTTP request sent, awaiting response... 404 Not Found
make: *** [Makefile:36: download] Error 8
```

**Comment by philpagel** [comment]
Thanks for reporting this. It seems my method of url construction broke.
It looks like Debian 11.3.0 also changed something in the boot mechanics – it seems headless installation is broken at the moment. Will look into that (issue #11).
