### ISSUE TITLE
several issues and fixes on macOS

### ISSUE THREAD

**Issue by vaaski** [philpagel/debian-headless#14]
Hello, I've tried to use this on macOS and ran into several issues and I feel like it's best if I document them here.

First off all,  `make install-depends` doesn't work on macOS because apt-get doesn't exist. Ignoring that, I ran into a couple of problems.

### cpio
I ran into `cpio: Append mode not yet supported.`, because the cpio version (bundled?) in macOS seems to be outdated. I installed cpio via homebrew and adjusted [this line](https://github.com/philpagel/debian-headless/blob/1547597e5c016189bc460eb221668606b259bd80/Makefile#L66) to the new path

```diff
- echo preseed.cfg | cpio -H newc -o -A -F ${TMP}/install.${ARCHFOLDER}/initrd 
+ echo preseed.cfg | /opt/homebrew/Cellar/cpio/2.14/bin/cpio -H newc -o -A -F ${TMP}/install.${ARCHFOLDER}/initrd
```

### genisoimage
It seems like genisoimage doesn't exist for macOS, but with some AI-assistance I found that [`mkisofs` is supposedly almost a drop-in replacement, minus the missing `-e` flag](https://www.phind.com/search?cache=f364ae60-1224-4a62-9130-b4fbc6c144c9). 

So I changed [this command](https://github.com/philpagel/debian-headless/blob/1547597e5c016189bc460eb221668606b259bd80/Makefile#L76-L82) to the following:

```bash
mkisofs -V ${LABEL} \
  -r -J -b isolinux/isolinux.bin -c isolinux/boot.cat \
  -no-emul-boot -boot-load-size 4 -boot-info-table \
  -eltorito-alt-boot \
  -eltorito-platform efi -eltorito-boot ${tmp} boot/grub/efi.img \
  -no-emul-boot \
  -o ${TARGET} ${TMP}
```

### isohybrid
Finally, `isohybrid` also doesn't exist, but once again [I consulted phind which presented `hdiutil` as an alternative](https://www.phind.com/search?cache=ac9a62e3-6be8-4466-9091-e3dbd750a76f).

So I changed [this line](https://github.com/philpagel/debian-headless/blob/1547597e5c016189bc460eb221668606b259bd80/Makefile#L83) to the following:

```diff
- isohybrid --uefi ${TARGET}
+ hdiutil convert -format UDRW -o ${TARGET}.img ${TARGET}
```

It finally seemed to finish executing successfully, and I am left with a... `.dmg` file??? Not what I expected and I honestly don't feel like troubleshooting any more, I guess I'll just search for that wireless keyboard dongle that I haven't seen in a while and install it the normal way...

I hope that this at least helped someone else to get closer though.
MfG

**Comment by philpagel** [comment]
Hi,
Thanks for the input. Yes, all of this has been written on/for LINUX – specifically for Debian derivatives. I have no access to MacOS so I can't really look into this. It may be possible to fix the issues for Mac OS without breaking it on LINUX but it may also be necessary to create a Mac specific fork if the differences are too large...
cu Phil

**Comment by philpagel** [comment]
Oh – and I have never seen a `.dmg` file before but it seems that this is an archive format used in MacOS. So maybe you just need to unpack it to get the iso? But I'm just guessing here – I'm not a mac expert...

**Comment by vaaski** [comment]
Yeah don't worry about it, in my case having the image be completely hands-off headless was an optional nice-to-have.

Just wanted to leave the troubleshooting I've done so far here for someone else to pick up in case they _need_ macOS support.

And yes `.dmg` is quite common on macOS, from my experience it's a pretty close mac-equivalent to an iso. Double clicking it mounts it as if it was an external disk and quite a few programs have their installer bundled in one. I guess `hdiutil` just uses it as a default.

Schönen Abend noch!
