### ISSUE TITLE
Missing packages on Raspbian (arm)

### ISSUE THREAD

**Issue by Surfer2010** [philpagel/debian-headless#2]
trying to use this on Raspbian will cause some problems with the following missing:
- genisoimage
- bsdtar
- isohybrid

**Comment by Surfer2010** [comment]
this solves 2 of those 3 Problems
- sudo apt-get install bsdtar
- sudo apt-get install genisoimage

didn't find a isohybrid yet

**Comment by philpagel** [comment]
Yes, as described in the README, you need to install the dependencies. How is that an issue?
