### ISSUE TITLE
Boot does not proceed beyond boot prompt on Debian Buster

### ISSUE THREAD

**Issue by zoof** [philpagel/debian-headless#4]
Wonderful project!

I have a very old laptop with a dying keyboard and when I ran across this, I decided to try this out to use it as a server.  Everything works except that the boot process stops at the boot prompt.  Fortunately, CTRL-M gets the boot process to continue.  Two possible sources for this problem are 1) the laptop is 32 bit and 2) it only has legacy USB support.

Interestingly, it works fine on a newer laptop so perhaps this is a Debian problem.

**Comment by philpagel** [comment]
Hm – interesting. Just to be sure: to what point exactly do you get? does it get stuck in BIOS, or do you get into grub, or even into the OS boot? I don't see why 32bit should be a problem. Neither do I see a reason for USB2 to not work.

**Comment by zoof** [comment]
Sorry, I meant no UEFI support not "legacy USB".  Here is a screenshot.

![IMG_0690](https://user-images.githubusercontent.com/1737483/103815176-f68cb180-5030-11eb-8702-97d8a8584321.JPG)

**Comment by philpagel** [comment]
No UEFI should not be an issue – in fact, it currently only works with legacy boot. Strange that it gets stuck in boot. Are you sure that you did set the architecture variable correctly?

**Comment by zoof** [comment]
```
$ cat config.txt 
# Configuration

# Name of source and target iso filenames
SOURCE = debian-10.7.0-i386-netinst.iso
TARGET = debian-10.7.0-i386-netinst-headless.iso

# Architecture settings
# amd64
#ARCH = amd
#QEMU = qemu-system-x86_64
# i386
ARCH = 386
QEMU = qemu-system-i386

# Preseeding file to use
PRESEED = preseed-en_US.cfg	# US locale and keyboard
#PRESEED =  preseed-en_DE.cfg	# US locale and keyboard, except country=DE
#PRESEED = preseed-de_DE.cfg	# german locale and keyboard

# Volume label for the target ISO image
LABEL = debian-hdl-inst

# Where to find the usb drive
# Caution: if this is set incorrectly you may ruin your system!
# uncomment and set carefully!
# use lsusb and/or the output of dmesg after plugging in your usb drive
# to find the correct device file
USBDEV = /dev/sdc
#USBDEV = /dev/null

# EOF
```

**Comment by philpagel** [comment]
Looks correct to me...

**Comment by philpagel** [comment]
Just gave it a try with the exact same image. It seems to work fine in qemu. I don't have a real i386 machine around anymore, so I have no way of trying. Very strange. What exact machine are you trying to install on? And what OS did you use to prepare the image?

**Comment by zoof** [comment]
It is an Acer Aspire One ZG5 and I used a Debian Buster system to construct the ISO.

**Comment by philpagel** [comment]
Debian Buster is certainly fine. I don't know this particular acer machine but why wouldn't it work? Right now, I am out of ideas...

**Comment by philpagel** [comment]
Maybe I do have an idea, after all:
You said the keyboard is dying? I checked [here](https://wiki.syslinux.org/wiki/index.php?title=Config#PROMPT)
and it says: 

> If flag_val is 0 (default), do not display the "boot:" prompt, unless either the [Shift] or the [Alt] key is pressed, 
> or unless either [Caps Lock] or [Scroll Lock] is set.

Is it possible that your defective keyboard is "pressing" one of those keys?

**Comment by zoof** [comment]
Thanks -- I can't rule that out although I am able to type with some of the keys.  I am certain that the Shift key is not pressed and neither the Caps Lock or the Scroll Lock are set.  But it may be that the Alt key is being pressed.

In any case, I have enough keyboard functionality to get it to proceed with the boot and install with an ssh session.  Many thanks!
