### ISSUE TITLE
No support for serial console (HP DL360 Gen10 and Debian 11.2)

### ISSUE THREAD

**Issue by fdik** [philpagel/debian-headless#9]
The image produced changes the text of Grub on the serial console, but the Debian installer still appears on the VGA.

**Comment by philpagel** [comment]
I am not sure what a serial console is supposed to show – I never tried installing via serial connection. 

And yes, the Debian installer is still present on a locally attached screen. That appears to be normal – I have no deeper insights into how/why Debian set it up that way. Perhaps the reasoning was to still allow for both paths of installation.

The main question is: does the remastered image get past network setup and can you get into the ssh installer to finish installation?

**Comment by fdik** [comment]
This fixes it for me:

```
diff --git a/grub.cfg.template b/grub.cfg.template
index 3c51664..a8bd04f 100644
--- a/grub.cfg.template
+++ b/grub.cfg.template
@@ -2,6 +2,6 @@ default=Install
 timeout=0
 menuentry 'Install' {
     set background_color=black
-    linux    /install.<ARCH>/vmlinuz vga=788 --- quiet
+    linux    /install.<ARCH>/vmlinuz vga=none console=ttyS0,115200n8 --- console=ttyS0,115200n8
     initrd   /install.<ARCH>/initrd.gz
 }
diff --git a/isolinux.cfg.template b/isolinux.cfg.template
index 4bd4fbd..4d440cf 100644
--- a/isolinux.cfg.template
+++ b/isolinux.cfg.template
@@ -2,4 +2,4 @@ DEFAULT install
   SAY Now booting the debian installer
 LABEL install
        kernel /install.<ARCH>/vmlinuz
-       append vga=788 initrd=/install.<ARCH>/initrd.gz --- quiet
+       append vga=none console=ttyS0,115200n8 initrd=/install.<ARCH>/initrd.gz --- quiet
```

**Comment by philpagel** [comment]
Ah – ok. Now I start grasping what you are after. If I understand you correctly, you want to carry out a headless installation via serial console, not ssh. Correct?

OK – that should be easy to fix, as you already pointed out. I'll look into incorporating that and probably make it configurable with respect to serial device and parameters. That should be a nice addition.

And just to make sure: you did not have trouble with the ssh installer side of things. Right?

**Comment by fdik** [comment]
No other issues. Thank you for this great project!

HP DL360 Gen10 has iLO5 and a Virtual Serial Port, which looks like a physical ttyS0 to all software. When configured it is possible to ssh the iLO and by doing this reach the console. This then can be used to install Debian through ssh.

**Comment by philpagel** [comment]
OK. Yes – I think that also works with iLO4 on my Miniserver Gen8...
Changing the Issue title a bit to reflect the real issue.
